spring:
  profiles:
    include: oauth, dev
  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    dnd.studyplanner: debug
    org.hibernate.SQL: debug
    org.hibernate.type: trace

jasypt:
  encryptor:
    bean: jasyptStringEncryptor